# environment.yml
name: sc_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - scanpy
  - anndata
  - scipy
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pyyaml
  - pip
  - r-base=4.4
  - r-matrix
  - r-yaml
  - r-devtools
  - rpy2
  - bioconductor-dropletutils
  - r-seurat=4.3
  - r-dplyr
  - bioconductor-singlecellexperiment
  - r-rcpp
  - bioconductor-biocparallel
  - pip:
    - git+https://github.com/constantAmateur/SoupX.git