site_name: Anatalyst
site_description: The Analysis Catalyst -- a modular analysis pipeline framework
site_author: Wesley Blashka
repo_url: https://github.com/UW-Brown-Lab/Anatalyst
repo_name: UW-Brown-Lab/Anatalyst

theme:
  name: material
  palette:
    scheme: slate
    primary: red
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

plugins:
  - search

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Configuration:
    - Overview: configuration/index.md
    - Examples: configuration/examples.md
  - Modules:
    - Overview: modules/index.md
    - DataLoading: modules/dataloading.md
    - QCMetrics: modules/qcmetrics.md
    - AmbientRNARemoval: modules/ambientrnaremoval.md
    - DoubletDetection: modules/doubletdetection.md
    - Filtering: modules/filtering.md
    - PearsonNormalization: modules/pearsonnormalization.md
    - DimensionalityReduction: modules/dimensionalityreduction.md
    - ReportGenerator: modules/reportgenerator.md
  - Customization:
    - Overview: customization/index.md
    - Creating New Modules: customization/new-modules.md
  - API Documentation:
    - Overview: api/index.md
    - Core Classes: api/core.md
    - Utilities: api/utils.md
  - Examples:
    - Overview: examples/index.md
    - PBMC Analysis: examples/pbmc.md
  - About: about/index.md