pipeline:
  name: minimal_qc_pipeline
  output_dir: ./output
  r_memory_limit_gb: 8
  figure_defaults:
    width: 8
    height: 6
  
modules:
  - name: data_loading
    type: DataLoading
    params:
      file_path: /path/to/sample_filtered_feature_bc_matrix.h5
      
  - name: qc_metrics
    type: QCMetrics
    params:
      mito_pattern: "^MT-"
      ribo_pattern: "^RP[SL]"
      
      