pipeline:
  name: Brown Lab Development Test Pipeline
  output_dir: ./output
  r_memory_limit_gb: 8
  figure_defaults:
    width: 8
    height: 6
  checkpointing:
    enabled: true
    modules_to_checkpoint:
      - all
    max_checkpoints: 9 
  
modules:
  - name: Load Data
    type: DataLoading
    params:
      file_path: ./tests/test_data/10k_PBMC_3p_nextgem_Chromium_Controller_filtered_feature_bc_matrix.h5
      
  - name: Pre-filtering QC Metrics
    type: QCMetrics
    params:
      mito_pattern: "^MT-"
      ribo_pattern: "^RP[SL]"

  - name: SoupX Decontamination
    type: AmbientRNARemoval
    params:
      raw_counts_path: ./tests/test_data/10k_PBMC_3p_nextgem_Chromium_Controller_raw_feature_bc_matrix.h5
      filtered_counts_path: ./tests/test_data/10k_PBMC_3p_nextgem_Chromium_Controller_filtered_feature_bc_matrix.h5
      ndims: 20

  - name: Doublet Detection
    type: DoubletDetection

  - name: Filter Outliers
    type: Filtering

  - name: Post-filtering QC Metrics
    type: QCMetrics
    params:
      mito_pattern: "^MT-"
      ribo_pattern: "^RP[SL]" 

  - name: Normalization
    type: PearsonNormalization

  - name: Dim Reduction
    type: DimensionalityReduction

  - name: Report Generator
    type: ReportGenerator

      
      